### PR TITLE
ajustes de layout diretamente em 'dist'

### PR DESCRIPTION
**Pull request by henrikcozza**
Ajustes no HTML para a página de demonstração.
image
image

### CODE REVIEW

**Review by RodrigoDornelles — CHANGES_REQUESTED** [review]
### questions to modify

 * move `dist/assets/logo` para `assets/logo.png`
 * remove vendors `dist/gamepadzilla.js` and `dist/vendors`
 * move html, css, and js files to `public/`
 
 ### general inquiries
 
 what is **prism**? is it really necessary?

**Comment by RodrigoDornelles** [comment]
> Prima.js is a library that converts text into span elements to apply syntax highlighting styling.

you can use an CDN like [https://www.jsdelivr**](https://www.jsdelivr.com/), because is not a direct project dependency.

@henrikcozza

**Comment by henrikcozza** [comment]
fix to PR

**Review by RodrigoDornelles — CHANGES_REQUESTED** [review]
* move `dist/index.html`  to `examples/index.html`
 * change to relative refs: `assets/css/styles.css` instead `../assets/css/styles.css`
 * remove package-lock.json
 * remove `assets/js/gamepadzilla.js`

**Comment by henrikcozza** [comment]
sorry but if you remove gamepadzilla.js the code will be broken.

**Comment by RodrigoDornelles** [comment]
> sorry but if you remove gamepadzilla.js the code will be broken.

you must follow the build flow, the `npm run build:example` command must put in the `dist/` path all the files to be published.

@henrikcozza

**Comment by RodrigoDornelles** [comment]
Thanks for trying to contribute!

unfortunately your pull request does not fit the project standard, see how it would be better structured in #32.

I ended up writing a new, simpler and more beautiful demo.

layout proposal was ugly, it was made by chatgpt.

@henrikcozza

**Pull request closed without merging**
